project_id = "lschdkhtymifmxjcbtvb"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.submit-quickscan]
    verify_jwt = false
  [functions.rescore-respondent]
    verify_jwt = false
